// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/task-watcher/pkg"
	"github.com/bborbe/time"
)

type BuildInfoMetrics struct {
	SetBuildInfoStub        func(*time.DateTime)
	setBuildInfoMutex       sync.RWMutex
	setBuildInfoArgsForCall []struct {
		arg1 *time.DateTime
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *BuildInfoMetrics) SetBuildInfo(arg1 *time.DateTime) {
	fake.setBuildInfoMutex.Lock()
	fake.setBuildInfoArgsForCall = append(fake.setBuildInfoArgsForCall, struct {
		arg1 *time.DateTime
	}{arg1})
	stub := fake.SetBuildInfoStub
	fake.recordInvocation("SetBuildInfo", []interface{}{arg1})
	fake.setBuildInfoMutex.Unlock()
	if stub != nil {
		fake.SetBuildInfoStub(arg1)
	}
}

func (fake *BuildInfoMetrics) SetBuildInfoCallCount() int {
	fake.setBuildInfoMutex.RLock()
	defer fake.setBuildInfoMutex.RUnlock()
	return len(fake.setBuildInfoArgsForCall)
}

func (fake *BuildInfoMetrics) SetBuildInfoCalls(stub func(*time.DateTime)) {
	fake.setBuildInfoMutex.Lock()
	defer fake.setBuildInfoMutex.Unlock()
	fake.SetBuildInfoStub = stub
}

func (fake *BuildInfoMetrics) SetBuildInfoArgsForCall(i int) *time.DateTime {
	fake.setBuildInfoMutex.RLock()
	defer fake.setBuildInfoMutex.RUnlock()
	argsForCall := fake.setBuildInfoArgsForCall[i]
	return argsForCall.arg1
}

func (fake *BuildInfoMetrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *BuildInfoMetrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.BuildInfoMetrics = new(BuildInfoMetrics)
